/**:
  ros__parameters:

    #Mass and inertia
    mass: 2.0 #kg
    ixx: 1
    ixy: 0
    ixz: 0
    iyy: 1
    iyz: 0
    iyy: 1

    #Geometry
    L_m: 0.1 #m : Distance between the CG and one of the main motors
    L_d: 0.1 #m : Distance between the CG and one of the depth motors

    #Main motors parameters
    alpha: 0.785 #Angle d'inclinaison des moteurs
    Kd_m: 0.001
    rot_max_m: 200 #rad/s

    #Depth motors parameters
    Kd_d: 0.001
    rot_max_d: 200 #rad/s

    #PWM
    PWM_0: 1500
    PWM_max: 2000
    PWM_min: 1000

    #Drag

    #PID parameters
    
    # Position controller parameters
    x_PID: {P: 5, I: 0.5, D: 1.5, I_max: 2.0 }
    y_PID: {P: 5, I: 0.5, D: 1.5, I_max: 2.0 }
    z_PID: {P: 5, I: 0.5, D: 0.5, I_max: 2.0 }
    
    # Velocity controller parameters
    vx_PID: {P: 2.5, I: 0.5, D: 1.5, I_max: 2.0 }
    vy_PID: {P: 2.5, I: 0.5, D: 1.5, I_max: 2.0 }
    vz_PID: {P: 5, I: 0.5, D: 0.5, I_max: 2.0 }

    # Attitude controller parameters
    roll_PID: {P: 5, I: 0.5, D: 1.5, I_max: 2.0 }
    pitch_PID: {P: 5, I: 0.5, D: 1.5, I_max: 2.0 }
    yaw_PID: {P: 5, I: 0.5, D: 0.5, I_max: 2.0 }
    
    # Rate controller parameters
    p_PID: {P: 2.5, I: 0.5, D: 1.5, I_max: 2.0 }
    q_PID: {P: 2.5, I: 0.5, D: 1.5, I_max: 2.0 }
    r_PID: {P: 5, I: 0.5, D: 0.5, I_max: 2.0 }

    #Saturation
    vx_max: 3 #m/s
    vy_max: 3
    vz_max: 3

    p_max: 1 #m/s^-2
    q_max: 1
    r_max: 1

    Fx_max: 100 #N
    Fy_max: 100
    Fz_max: 100

    Mx_max: 100 #N*m
    My_max: 100
    Mz_max: 100